# Appended to page title
title: "ItsDiabetes"


# CSS Configuration Settings
normalize: true  # Import normalize? (v8.0.1, github.com/necolas/normalize.css)
bootstrap: false  # Import bootstrap? (v5.1.3, getbootstrap.com)
customCSS: true # Import custom CSS?

# JS Configuration settings
customJS: false # Import custom JS?

sass:
  style: compressed

exlude:
  .idea/*
